[package]
name = "openvm-reth-verifier-bench"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true
version.workspace = true

[dependencies]
openvm-circuit.workspace = true
openvm-native-circuit = { workspace = true }
openvm-sdk = { workspace = true }
openvm-continuations = { workspace = true }
openvm-native-recursion = { workspace = true }
openvm-stark-sdk.workspace = true

bitcode.workspace = true
clap = { version = "4.5.7", features = ["derive", "env"] }

[lints]
workspace = true

[features]
default = ["metrics"]
metrics = ["openvm-circuit/metrics"]
tco = ["openvm-sdk/tco"]
evm-prove = ["openvm-sdk/evm-prove"]
evm-verify = ["evm-prove", "openvm-sdk/evm-verify"]
jemalloc = ["openvm-sdk/jemalloc"]
nightly-features = ["openvm-sdk/nightly-features"]
