[package]
name = "openvm-reth-benchmark-bin"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true
version.workspace = true

[dependencies]
clap_builder = "4.5.34"
eyre.workspace = true
openvm-reth-benchmark = { workspace = true, default-features = false }
openvm-stark-sdk.workspace = true
tokio.workspace = true

[lints]
workspace = true

[features]
default = ["openvm-reth-benchmark/default"]
metrics = ["openvm-reth-benchmark/metrics"]
perf-metrics = ["openvm-reth-benchmark/perf-metrics"]
mimalloc = ["openvm-reth-benchmark/mimalloc"]
jemalloc = ["openvm-reth-benchmark/jemalloc"]
nightly-features = ["openvm-reth-benchmark/nightly-features"]
halo2-asm = ["openvm-reth-benchmark/halo2-asm"]
