# # Copy to config.toml for local patches
# [net]
# git-fetch-with-cli = true

# # [patch."https://github.com/openvm-org/stark-backend.git"]
# # openvm-stark-backend = { git = "ssh://git@github.com/openvm-org/stark-backend.git", tag = "v1.1.2" }
# # openvm-stark-sdk = { git = "ssh://git@github.com/openvm-org/stark-backend.git", tag = "v1.1.2" }

# [patch."https://github.com/openvm-org/openvm.git"]
# openvm-benchmarks-prove = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# # OpenVM
# openvm-sdk = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# cargo-openvm = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-mod-circuit-builder = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-poseidon2-air = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-circuit-primitives = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-circuit-primitives-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-build = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-instructions = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-instructions-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-macros-common = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-platform = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-circuit-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }

# # Extensions
# openvm-algebra-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-algebra-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-algebra-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-algebra-moduli-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-algebra-complex-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-bigint-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-bigint-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-bigint-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-ecc-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-ecc-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-ecc-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-ecc-sw-macros = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-keccak256-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-keccak256-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-keccak256-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-sha256-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-sha256-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-sha256-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-native-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-native-compiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-native-compiler-derive = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-native-recursion = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-pairing-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-pairing-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-pairing-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-rv32-adapters = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-rv32im-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-rv32im-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-rv32im-guest = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }

# # Guest Libs
# k256 = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# p256 = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# ruint = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-keccak256 = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-sha2 = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
# openvm-pairing = { git = "ssh://git@github.com/openvm-org/openvm.git", tag = "v1.4.0" }
